spring:
  application:
    name: pascal-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.pascal.ai: debug

server:
  port: 8080